audit_header: false
title: "Guaranteed Offer"
description: Jerry Van Leeuwen, a top Real Estate Agent in Tri-Cities Area, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
client:
  name: Jerry Van Leeuwen
  title:
  license_number:
  about_markdown: >-
    Jerry has been helping families and individuals find and secure their dream
    homes for many years now. His family has been his driving force and they
    inspire him to maintain a strong work ethic. Jerry's previous experience as
    a paramedic has helped him develop a passion for the positive aspects of
    life.
  brand: Van Leeuwen Real Estate Advisors
  brokerage: Keller Williams Golden Triangle
  market: Tri-Cities Area
  address: '1165 Franklin Blvd Cambridge, ON N1R 8E1, Canada'
  phone: 519-208-6026
  phone_type:
  phone2:
  phone2_type:
  email: GetResults@VanleeuwenAdvisors.com
  url: 'http://www.VLAHomeListings.com'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  logo_width: 40rem
  mobile_logo_width: 150px

site_colors:
  brand_color: '#0f75bc'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
